language: python

services:
  - docker

matrix:
  include:
    - python: 3.5
      dist: xenial
    - python: 3.6
      dist: xenial
    - python: 3.7
      dist: xenial


# command to install dependencies
before_install:
  - pip install -U pip wheel
  - pip install -r requirements.txt
  - pip install -r requirements_extra_tf.txt
  - pip uninstall -y tensorflow-gpu
  - pip install tensorflow==1.13.1
  - pip install -r requirements_extra_torch.txt
  - pip install coverage
  - pip install codecov

install:
  - pip install .

# command to run tests
script:
  - coverage run -m unittest
  # - codecov
